name: game_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  pointycastle: ^3.9.1
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.0.6
  shared_preferences_web: ^2.0.4
  collection: ^1.16.0

  google_fonts: ^6.2.1
  http: ^1.2.1
  bcrypt: ^1.1.3
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

  geolocator: ^12.0.0
  geolocator_apple: ^2.3.7
  geolocator_android: ^4.6.0
  geolocator_web: ^4.0.0
  geolocator_linux: ^0.2.1
  geolocator_windows: ^0.2.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  nominatim_flutter: ^0.0.3
  osm_nominatim: ^3.0.0

  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true
  assets: 
    - assets/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900
